import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Grid } from "@mui/material";
import { Footer } from "./Layouts/footer";
import { TopNav } from "./Layouts/top-nav";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "ecoysoft environment Inc.",
  description: "The next level brand creator",
=======
  title: "Ecoysoft",
  description: "Generated by create next app",
>>>>>>> why-choose-us
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
<<<<<<< HEAD
        <Grid
          container
          direction="column"
          justifyContent="space-between"
          alignItems="center"
          style={{ width: "100%" }}
        >
=======
        <Grid container direction="column" alignItems="center">
>>>>>>> why-choose-us
          <TopNav />
          {children}
          <Footer />
        </Grid>
      </body>
    </html>
  );
}
